### ISSUE TITLE
Pdf

### ISSUE THREAD

**Issue by cege72** [ltn22/PLIDO_BOOK#1]
Hello, Impossible de télécharger les books pdf (je suis sur tablette apple)

**Comment by ltn22** [comment]
Bonjour, 

Effectivement, je viens d'essayer en anonyme sur un ipad et je n'ai pas la visualisation du fichier PDF.  Par contre en cliquant sur les ... à droite on peut télécharger le fichier et le visualiser et le transférer dans "Livres".

Dites moi si ca marche et bonne lecture.

Laurent
