### ISSUE TITLE
Lopy and macOS pour prochaine session

### ISSUE THREAD

**Issue by RaspChris** [ltn22/PLIDO_BOOK#2]
Bonjour, 
Merci beaucoup pour ce PDF tout à fait génial !!! (liens internes, vers youtube, la totale).

Vous indiquez en note (9.2 Installation d'Atom, p.105) des soucis avec Atom et Pymakr.... Sur macOS, les soucis se sont intensifiés. La dernière version de macOS 12.3.1 n'accepte plus que Atom 1.60.0 et Pycom a du sortir, ces derniers jours, une nouvelle version de Pymakr (2.3.7). Mais elle ne fonctionne pas encore chez moi et je suis en contact avec Pycom pour qu'ils essaient de résoudre le problème. Cela risque d'être un peu long...

Merci encore.
Bonne nouvelle session.
Christine

**Comment by ltn22** [comment]
Bonjour,

Merci pour vos commentaires, Atom devient de plus en plus délicat à utiliser, j'ai réussi a l'installer sur mon Mac il y a un mois, mais un collègue n'a pas pu la semaine dernière. Dans ce cas, on peut utiliser visual code studio avec pymakr, l'interface est moins ergonomique mais c'est plus stable. ET tenez nous au courant des évolutions.

Laurent

**Comment by RaspChris** [comment]
Bonjour,
Donc résultat des courses : Il existe maintenant une version 2.3.7 de Pymakr qui fonctionne sur Atom 1.6.00 (qui s'installe sur MacOs 12.3). J'ai du mettre à jour le firmware du Lopy4 : https://docs.pycom.io/updatefirmware/device/ (en effaçant ce qui était sur le Lopy). 
(VCS ne me parlait pas du tout !!!!). Mais, ça y est, c'est reparti.
A bientôt.
Christine
